import * as fs from "fs";
import * as path from "path";
import * as os from "os";
import { z } from "zod";
import { registerTool } from "./registry.js";

// ---------------------------------------------------------------------------
// Source: ~/.claude/usage-dashboard/usage-data.json
// Generated by parse-logs.mjs from Claude Code session JSONL files.
// Includes all sessions across all projects, with accurate token counts
// including cache_creation and cache_read tokens.
// ---------------------------------------------------------------------------

const USAGE_DATA_PATH = path.join(os.homedir(), ".claude/usage-dashboard/usage-data.json");

interface SessionUsage {
  input_tokens: number;
  output_tokens: number;
  cache_creation_input_tokens: number;
  cache_read_input_tokens: number;
}

interface Session {
  sessionId: string;
  project: string;
  model: string;
  start: string;
  messages: number;
  usage: SessionUsage;
  cost: number;
}

interface UsageData {
  generated: string;
  sessions: Session[];
}

function loadUsageData(): UsageData | null {
  try {
    const raw = fs.readFileSync(USAGE_DATA_PATH, "utf-8");
    return JSON.parse(raw) as UsageData;
  } catch {
    return null;
  }
}

function isChrisAssistantSession(session: Session): boolean {
  const project = session.project ?? "";
  return project === "chris-assistant" || project.startsWith("chris-assistant--");
}

function getSessionsForDate(sessions: Session[], date: string): Session[] {
  return sessions.filter((s) => isChrisAssistantSession(s) && s.start.startsWith(date));
}

// ---------------------------------------------------------------------------
// Aggregation
// ---------------------------------------------------------------------------

interface ModelStats {
  sessions: number;
  messages: number;
  input_tokens: number;
  output_tokens: number;
  cache_creation_input_tokens: number;
  cache_read_input_tokens: number;
  cost: number;
}

function aggregateByModel(sessions: Session[]): Record<string, ModelStats> {
  const byModel: Record<string, ModelStats> = {};
  for (const s of sessions) {
    const model = s.model || "unknown";
    if (!byModel[model]) {
      byModel[model] = {
        sessions: 0,
        messages: 0,
        input_tokens: 0,
        output_tokens: 0,
        cache_creation_input_tokens: 0,
        cache_read_input_tokens: 0,
        cost: 0,
      };
    }
    byModel[model].sessions++;
    byModel[model].messages += s.messages ?? 0;
    byModel[model].input_tokens += s.usage?.input_tokens ?? 0;
    byModel[model].output_tokens += s.usage?.output_tokens ?? 0;
    byModel[model].cache_creation_input_tokens += s.usage?.cache_creation_input_tokens ?? 0;
    byModel[model].cache_read_input_tokens += s.usage?.cache_read_input_tokens ?? 0;
    byModel[model].cost += s.cost ?? 0;
  }
  return byModel;
}

function rollingAverage(sessions: Session[], endDate: string, days = 7): number {
  let total = 0;
  let daysWithData = 0;
  for (let i = 0; i < days; i++) {
    const d = new Date(endDate);
    d.setDate(d.getDate() - i);
    const ds = d.toISOString().slice(0, 10);
    const daySessions = getSessionsForDate(sessions, ds);
    if (daySessions.length > 0) {
      total += daySessions.reduce((sum, s) => sum + (s.cost ?? 0), 0);
      daysWithData++;
    }
  }
  return daysWithData > 0 ? total / daysWithData : 0;
}

// ---------------------------------------------------------------------------
// Formatting
// ---------------------------------------------------------------------------

function formatTokenCount(n: number): string {
  if (n >= 1_000_000) return `${(n / 1_000_000).toFixed(1)}M`;
  if (n >= 1_000) return `${(n / 1_000).toFixed(1)}k`;
  return String(n);
}

function freshness(generated: string): string {
  const gen = new Date(generated);
  const now = new Date();
  const diffMins = Math.round((now.getTime() - gen.getTime()) / 60_000);
  if (diffMins < 2) return "just now";
  if (diffMins < 60) return `${diffMins}m ago`;
  const h = Math.floor(diffMins / 60);
  const m = diffMins % 60;
  return m > 0 ? `${h}h ${m}m ago` : `${h}h ago`;
}

function formatDayReport(date: string, data: UsageData): string {
  const sessions = getSessionsForDate(data.sessions, date);

  if (sessions.length === 0) {
    return `📊 **Token Usage (chris-assistant) — ${date}**\n\nNo sessions recorded.\n\n_Data updated ${freshness(data.generated)}_`;
  }

  const byModel = aggregateByModel(sessions);
  const totalCost = sessions.reduce((sum, s) => sum + (s.cost ?? 0), 0);
  const totalMessages = sessions.reduce((sum, s) => sum + (s.messages ?? 0), 0);
  const avg = rollingAverage(data.sessions, date);

  const lines: string[] = [`📊 **Token Usage (chris-assistant) — ${date}**`];

  const sorted = Object.entries(byModel).sort((a, b) => b[1].cost - a[1].cost);
  for (const [model, stats] of sorted) {
    lines.push("");
    lines.push(`🤖 **${model}**`);
    lines.push(`   ↳ ${stats.sessions} sessions · ${stats.messages} msgs`);
    lines.push(`   ↳ in: ${formatTokenCount(stats.input_tokens)} · out: ${formatTokenCount(stats.output_tokens)} · cache read: ${formatTokenCount(stats.cache_read_input_tokens)}`);
    lines.push(`   💰 **$${stats.cost.toFixed(2)}**`);
  }

  lines.push("");
  lines.push(`**Total:** $${totalCost.toFixed(2)} · ${totalMessages} msgs · ${sessions.length} sessions`);
  lines.push(`**7-day avg:** $${avg.toFixed(2)}/day`);
  lines.push(`\n_Data updated ${freshness(data.generated)}_`);

  return lines.join("\n");
}

function formatMultiDayReport(endDate: string, days: number, data: UsageData): string {
  const lines: string[] = [`📊 **Token Usage (chris-assistant) — last ${days} days**`];

  let grandTotal = 0;
  let daysWithData = 0;

  for (let i = days - 1; i >= 0; i--) {
    const d = new Date(endDate);
    d.setDate(d.getDate() - i);
    const ds = d.toISOString().slice(0, 10);
    const daySessions = getSessionsForDate(data.sessions, ds);
    if (daySessions.length === 0) continue;

    const dayCost = daySessions.reduce((sum, s) => sum + (s.cost ?? 0), 0);
    const dayMessages = daySessions.reduce((sum, s) => sum + (s.messages ?? 0), 0);
    grandTotal += dayCost;
    daysWithData++;

    lines.push(`\n**${ds}** — $${dayCost.toFixed(2)} · ${dayMessages} msgs`);

    const byModel = aggregateByModel(daySessions);
    const sorted = Object.entries(byModel).sort((a, b) => b[1].cost - a[1].cost);
    for (const [model, stats] of sorted) {
      lines.push(`  ${model}: ${stats.sessions} sessions · $${stats.cost.toFixed(2)}`);
    }
  }

  if (daysWithData === 0) {
    return `📊 **Token Usage (chris-assistant) — last ${days} days**\n\nNo sessions recorded.\n\n_Data updated ${freshness(data.generated)}_`;
  }

  lines.push("");
  lines.push(`**Total:** $${grandTotal.toFixed(2)} over ${daysWithData} active days`);
  lines.push(`**Daily avg:** $${(grandTotal / daysWithData).toFixed(2)}/day`);
  lines.push(`\n_Data updated ${freshness(data.generated)}_`);

  return lines.join("\n");
}

// ---------------------------------------------------------------------------
// Tool registration
// ---------------------------------------------------------------------------

registerTool({
  name: "get_usage_report",
  category: "always",
  description:
    "Get a token usage and cost report for the chris-assistant Claude Code project. " +
    "Reads from ~/.claude/usage-dashboard/usage-data.json. Defaults to today. " +
    "Use this when Chris asks about API costs, token usage, or model spending.",
  zodSchema: {
    date: z.string().optional().describe("Date in YYYY-MM-DD format. Defaults to today."),
    days: z.number().optional().describe("Number of days to include (for multi-day summaries). Defaults to 1."),
  },
  jsonSchemaParameters: {
    type: "object",
    properties: {
      date: { type: "string", description: "Date in YYYY-MM-DD format. Defaults to today." },
      days: { type: "number", description: "Number of days to include. Defaults to 1." },
    },
    required: [],
  },
  execute: async (args: { date?: string; days?: number }): Promise<string> => {
    const data = loadUsageData();
    if (!data) {
      return "❌ Could not read usage data. Check ~/.claude/usage-dashboard/usage-data.json exists.";
    }

    const days = args.days ?? 1;
    const date = args.date ?? new Date().toISOString().slice(0, 10);

    if (days === 1) {
      return formatDayReport(date, data);
    }

    return formatMultiDayReport(date, days, data);
  },
});

console.log("[tools] get_usage_report registered");
